version: "3.3"
services:
  db:
    image: postgres:12.0-alpine
    container_name: projeto-nati-db
    environment:
      POSTGRES_USER: projetostore
      POSTGRES_PASSWORD: projetostore
      POSTGRES_DB: projetostore
    volumes:
      - db-data:/var/lib/postgres
    restart: always
    ports: 
      - "5432:5432"
    networks:
      - backend
  api:
    build: "./"
    container_name: projeto-nati-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/projetostore
      SPRING_DATASOURCE_USERNAME: projetostore
      SPRING_DATASOURCE_PASSWORD: projetostore
    networks: 
      - backend

volumes:
  db-data:


networks:
  backend: